### ISSUE TITLE
Using JSONSchema to define your data

### ISSUE THREAD

**Issue by allevo** [mafintosh/turbo-json-parse#3]
Like [fast-json-stringify](https://github.com/fastify/fast-json-stringify) does, JSONSchema fits better than own schema definition language.

Maybe a subset of JSONSchema feature could be great to support!

**Comment by mafintosh** [comment]
Yes 100% agree. Just the first version in one sitting so room for improvement :)

**Comment by allevo** [comment]
I'll be happy to help you!
If you want I'll prepare a PR

**Comment by mafintosh** [comment]
Yea that'd be great!

**Comment by mafintosh** [comment]
fixed in master (mostly by you!) :)

**Comment by anurbol** [comment]
Hi, I am sorry, is current schema now compliant with the said format? I just read readme.md and it says schema uses different format e.g. 'number' instead of 'integer'
