### ISSUE TITLE
[Bug Report] there will be a problem if i send the json from python client

### ISSUE THREAD

**Issue by trylovetom** [mafintosh/turbo-json-parse#33]
### Description
I create the node.js express server as backend. When I get the request with json data from httpie, there will be a little different between java, javascript.

### Expected Behavior
**what I get on my server**
```sh
{"hello":"world"}
```

### Actual Behavior
**what I get on my server**
```sh
{"hello": "world"}
---------^--------- trailing whitespaces here
```

**and throw the error**
```sh
Error: Unterminated string
    at parseString (eval at line.toFunction (/Users/tzu-yen/Documents/TonJS/node_modules/generate-function/index.js:172:21), <anonymous>:3:23)
    at parse (eval at line.toFunction (/Users/tzu-yen/Documents/TonJS/node_modules/generate-function/index.js:172:21), <anonymous>:11:17)
    at Object.readJSON (/Users/tzu-yen/Documents/TonJS/packages/catapult/src/index.ts:33:10)
    at /Users/tzu-yen/Documents/TonJS/example/single.ts:8:18
    at /Users/tzu-yen/Documents/TonJS/packages/ton/dist/index.js:298:28
```

There will be a problem, when I use the parser from third party parser such as [turbo-json-parse](https://github.com/mafintosh/turbo-json-parse).

### Environment
- Node.js v14.2.0
- express v4.17.1
- httpie v2.1.0
- macOS (Catalina v10.15.4)
  - MacBook Pro (Retina, 13-inch, Early 2015)
  - 2.7 GHz Core x2
  - 8 GB DDR3 Ram x1

**httpie command**
```sh
http post :3000 hello=world
```

**my source code**
```js
const express = require('express')
const bodyParser = require('body-parser')
const turbo = require('turbo-json-parse')
const parser = turbo(  {
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
})

// create server
const app = express()

// add middleware
app.use(bodyParser.raw())
app.use(function (req, res, next) {
  console.log(req.body.toString()) // print the body from client

  parser(req.body.toString())

  next()
})
```

**Comment by trylovetom** [comment]
Any Update @mafintosh

**Comment by mafintosh** [comment]
Thanks for the issue, let me have a look

**Comment by mafintosh** [comment]
Set `prettyPrinted: true` in the options for json with whitespace support
